### ISSUE TITLE
Remove 'undo commit' command from gitlens inspect

### ISSUE THREAD

**Issue by d13** [gitkraken/vscode-gitlens#2746]
### Discussed in https://github.com/gitkraken/vscode-gitlens/discussions/2745

<div type='discussions-op-text'>

<sup>Originally posted by **mdj-uk** June 16, 2023</sup>
When in the gitlens inspect file history, or commit history, there is a button to undo the latest commit (the first icon from the left):
<img width="305" alt="image" src="https://github.com/gitkraken/vscode-gitlens/assets/101579982/7b829ebd-cf0f-45c1-9dbb-fc99de4e379d">

I find it very easy to hit that accidentally, which makes me scared to use just about any gitlens feature. 

Is there any way to remove it, or to require a confirmation step? I couldn't find any option in the extension settings.</div>

**Comment by yurymann** [comment]
Is it possible to bump the priority of this, please? 
As a new GitLens user, I discovered this "feature" accidentally yesterday and was upleasantly surprised. Have to pay explicit attention now to not hitting it every time I navigate in that panel. 

Any action affecting working copy should ask for a confirmation.

**Comment by eamodio** [comment]
Fixed by 056e19ccad86d12de3da8cc7ac49ac2480609cfe (wrong commit message)

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's (`v2023.12.05xx`) pre-release edition of GitLens? Thank you so much!

You can switch to the pre-release edition of GitLens, by clicking on the "Switch to Pre-Release version of this extension" from the Extensions view.

![image](https://user-images.githubusercontent.com/641685/228608740-6071bc19-7b1a-44c8-843f-d2af44d6114b.png)

**Comment by yurymann** [comment]
@eamodio I've just tried `v2023.12.504` and didn't notice any change: the same Undo Commit button is avilable and when pressed, updates the working copy. What was supposed to change? 

Sorry, can't attach the screenshot as I was testing it on the work machine.

**Comment by eamodio** [comment]
@yurymann Are you looking at this in the _File History_ or _Line History_ views?

**Comment by mdj-uk** [comment]
For me it's removed from the file history:
<img width="476" alt="image" src="https://github.com/gitkraken/vscode-gitlens/assets/101579982/b8602527-7cb7-4668-8d45-f93d06fff76c">

but still present in the commit history:
<img width="481" alt="image" src="https://github.com/gitkraken/vscode-gitlens/assets/101579982/7aa884b7-3ea7-4342-bbb5-021ec7d64137">
That's after selecting the pre-release version of the extension v2023.12.704.

Is the plan to remove it from the commit widget as well?

**Comment by eamodio** [comment]
No, this is only for the _File History_ & _Line History_. You can open another issue for the _Commits_ view, but given the usage and intent in that view I'm not convinced on removing that option, but if there is enough community agreement we can revisit.
