### ISSUE TITLE
`gitlens.remotes` no longer takes effect when defined in project's `.vscode/settings.json` file

### ISSUE THREAD

**Issue by sjdemartini** [gitkraken/vscode-gitlens#2760]
### Description

1. With GitLens version v2023.6.2005
2. With a `.vscode/settings.json` file that defines the `"gitlens.remotes"` field, like:
    ```
    "gitlens.remotes": [
      {
        "domain": "my.custom.example.com",
        "type": "GitLab"
      }
    ],
    ```

Historically, this was sufficient (for the past couple years or so), and the remote would take effect for the whole project. Now, it seems I need to separately define this setting instead/externally in my own `.code-workspace` workspace settings file in order for it to take effect. (That's rather inconvenient for our shared project where all developers should benefit from the same remote setup.) With the definition above only in the `.vscode/settings.json`, all remote-associated commands like `GitLens: Copy Remote File URL`, `GitLens: Copy Remote Commit URL`, etc. do not work:

![image](https://github.com/gitkraken/vscode-gitlens/assets/1647130/a60b1040-a115-4471-b167-f33e2c3326ad)

Separately, clicking that `See how to configure a custom remote provider...` link goes to https://github.com/gitkraken/vscode-gitlens#remote-provider-integration-settings-, which is dead (the anchor no longer exists). There is no help about how to resolve.

Other GitLens behavior still works fine (I can view inline blame, look at file details, etc.).

### GitLens Version

v2023.6.2005

### VS Code Version

Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:58:52.392Z (1 wk ago)
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.5.0

### Git Version

git version 2.30.0

### Logs, Screenshots, Screen Captures, etc

For what it's worth, I do see a single line in the GitLens output:

```
[2023-06-21 18:50:41.427] [GIT  ] [/Users/sdemartini/vscode_workspaces] git rev-parse --show-toplevel • Command failed: /usr/local/bin/git -c core.quotepath=false -c color.ui=false rev-parse --show-toplevel • not a git repository (or any of the parent directories): .git [54ms]
```

I have my `foo.code-workspace` file in the `/Users/sdemartini/vscode_workspaces` directory, which is not where the actual repo is (the `folders` for the workspace point to a different path), but this seems likely to be unrelated.

**Comment by d13** [comment]
@sjdemartini  @DanaGoyette We'll get that link update, thanks! The correct link is: https://help.gitkraken.com/gitlens/gitlens-settings/#remote-provider-integration-settings

**Comment by sgarcia-dev** [comment]
Experiencing this same issue, correctly configured `gitlens.remotes` in both my workspace config file, project, and user config file, and still getting that `no auto-detected or configured remote providers found` warning when I try to view a file on the remote.

Worse part is Gitlens is working properly beyond that, since the Gitlens remote view looks and browses fine, and that the couple of bug reports I found via google from 2021 and 2022 were all closed when the issue still happens.

**Comment by koenieee** [comment]
Same issue here, please fix it. Looked for a day through all the issues, I can't get it to work.

**Comment by ahammer-sc** [comment]
Also came here to say I am experiencing this issue. went through several different attempts to get it to work. it was working before but now just stopped working.

**Comment by lmao12** [comment]
I was able to get this working. I ran `$ git remote -vv` to see what my git path was. Based on that, I set this code in my `~/Library/Application Support/Code/User/settings.json` file:

```
    "gitlens.remotes": [
        {
            "regex": "git@(.+):(.+).git",
            "type": "GitHub",
        }
    ]
```

The captured snippets inside both `(.+)` combined to make my Github URL (i.e. "github.my-company.com/repo") so you may need to play around with the regex.

I did NOT need the additional `"gitlens.integrations.enabled": true` option.

**Comment by Actticus** [comment]
Any updates here? Copy Remote File URL still didnt work with 'domain' setting

**Comment by andrew-hardin** [comment]
This is working for me on GitLens `v13.6.0` after following the examples in the [docs](https://help.gitkraken.com/gitlens/gitlens-settings/#remote-provider-integration-settings). However, the instructions are missing a critical step: **restart VSCode** after adding the remote.

**Comment by kshashank231** [comment]
> "gitlens.remotes": [
>         {
>             "regex": "git@(.+):(.+).git",
>             "type": "GitHub",
>         }
>     ]

This worked for me. Thanks!

**Comment by WinjayYu** [comment]
> I was able to get this working. I ran `$ git remote -vv` to see what my git path was. Based on that, I set this code in my `~/Library/Application Support/Code/User/settings.json` file:
> 
> ```
>     "gitlens.remotes": [
>         {
>             "regex": "git@(.+):(.+).git",
>             "type": "GitHub",
>         }
>     ]
> ```
> 
> The captured snippets inside both `(.+)` combined to make my Github URL (i.e. "github.my-company.com/repo") so you may need to play around with the regex.
> 
> I did NOT need the additional `"gitlens.integrations.enabled": true` option.

It works for me, thank you very much!

**Comment by gwinkless** [comment]
@d13 when you removed the bug tag were you saying that you believe the original report (that setting gitlens.remotes in the project's .vscode folder does not work) is fixed?

Seems like the original bug report was hijacked, and the thing that's fixed is the secondary issue where the link to the documentation was in error.

Unless there's a non-obvious way to set the remotes for a project in the folder settings.json? Or is it actually by-design?

To clarify: I can set gitlens.remotes in the project workspace, close vscode, reopen vscode and the "open commit on remote" works. I can then cut the setting from the project workspace, paste the exact same setting into the .vscode settings.json file, close vscode, reopen vscode and "open commit on remote" fails with "no autodetected or configured remote providers found"

**Comment by Utopia-Zzzz** [comment]
Excuse me，

How can i fix it when my git website has a port number？

git cmd use 3022，bug website use 3000，like：
`
origin  ssh://git@xxx:3022/xx/xxxx.git
`
but website is : 
`
http://xxx:3000/xx/xxxx
`

` "regex": "git@(.+):3022/(.+).git" `
using this will make `See how to configure a custom remote provider...` disappear.
But open link with out port number.
what should i do ?

**Comment by d13** [comment]
If this issue is reproducible, can one of you please enable debug logging by running from _GitLens: Enable Debug Logging_ from the Command Palette (<kbd>F1</kbd> or <kbd>ctrl/cmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>). This will enable logging to the _GitLens_ and _GitLens (Git)_ channel in the _Output_ pane.

Once enabled, please reproduce the issue, and attach the log from both the _GitLens_ and _GitLens (Git)_ channels.

Thank you!

**Comment by eamodio** [comment]
@gwinkless I've tried setting `gitlens.remotes` in both user/workspace settings and in a `.vscode/settings.json` in the folder and I'm seeing the remotes loaded in all cases.

Can you still reproduce this on the latest version? If so, can you provide exact steps and/or a reproducible sample? Thanks!

**Comment by gwinkless** [comment]
> [@gwinkless](https://github.com/gwinkless) I've tried setting `gitlens.remotes` in both user/workspace settings and in a `.vscode/settings.json` in the folder and I'm seeing the remotes loaded in all cases.
> 
> Can you still reproduce this on the latest version? If so, can you provide exact steps and/or a reproducible sample? Thanks!

@eamodio It's now picking up the settings from the project .vscode folder for me. I didn't change anything.

Not sure if the code changed or if this is a transient, if it starts happening again I'll grab the debug logs for it.

**Comment by eamodio** [comment]
@gwinkless Thanks! I'm going to close this then, but we can re-open if it becomes reproducible again.
