### ISSUE TITLE
Improve graph filter paging and loading

### ISSUE THREAD

**Issue by justinrobots** [gitkraken/vscode-gitlens#4515]
### Description

When searching/filtering the graph and more than one page of results are returned, navigating to more history is not easy.

Navigating with up/down arrows works inconsistently.

- maybe add a "show more results" button at the bottom so it is clear that there is more to see. get rid of "infinite scroll" mode in this case?

**Comment by lexandrop** [comment]
Completely agree. Search/filter are the main features I use the "Commit Graph" for, and for large enough repos it feels unusable. Sometimes it's much faster and easier to find the commit I'm looking for manually in a sidebar, or via the "GitLens: Search commit" VSCode command.

**Comment by eamodio** [comment]
This was address in the overhaul of Graph search in 17.8

**Comment by nikolay-1986** [comment]
### Verification result: Failed

There is a logic error in the graph search implementation located in `graph.ts`. The condition checking the search limit uses `count > limit`, which combined with the counter incrementing after the check so it allows more items to be processed than requested. Additionally, due to the asynchronous nature of the stream parser, multiple items may be buffered and added to the results before the abort signal stops the flow.

#### Reproduction Steps:
- Open VS Code Settings.
- Set `gitlens.graph.searchItemLimit` to 1.
- Open the GitLens Commit Graph.
- Perform a search that gives multiple matches (e.g., search for a frequent author).
- Observe: The graph displays multiple results (e.g., 4 or 7) instead of exactly 1.

<img width="1568" height="890" alt="Image" src="https://github.com/user-attachments/assets/138fbc5c-5b9e-489c-8a64-c3d9102d196f" />

<img width="1560" height="892" alt="Image" src="https://github.com/user-attachments/assets/93b08c8c-f193-4180-a7b3-e85c563b35ea" />

<img width="1551" height="1096" alt="Image" src="https://github.com/user-attachments/assets/12ffd384-3dd9-4e95-bbf9-30b06dff85c5" />


#### Ai Fix Recommendation:
Update the loop termination condition to be strict.
Change:

`if (limit && count > limit) { ... }`

To:

`if (limit && count >= limit) { ... }`

This ensures the loop breaks immediately once the limit is reached, preventing additional items from being processed or returned.

**Comment by eamodio** [comment]
@nikolay-1986 Thanks for the investigation. I've fixed the "off-by-one" case, but since the search is streamed in batches the limits aren't hard and fast rules and I don't think it is worth artificially limiting (truncating) the data, as we've already paid the cost to find it just to hit the limit.

**Comment by nikolay-1986** [comment]
Verification: Passed

**Note**: the latest fix for the "off-by-one" error has improved the behavior: setting a search limit of 1 now results in 2 commits being displayed (previously it was 4-7). While this is closer to the expected behavior and better than before, it is still not strictly adhering to the limit of 1.

<img width="1221" height="551" alt="Image" src="https://github.com/user-attachments/assets/9d8b0c36-d75e-4769-b1ad-caf594dd6600" />
